version: "3"

services:
  registry:
    container_name: registry
    restart: always
    image: registry:latest
    ports:
      - 443:443
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:443
      REGISTRY_HTTP_HOST: "https://${DOMAIN}"
      REGISTRY_LOG_ACCESSLOG_DISABLED: "true"
      REGISTRY_LOG_LEVEL: "error"
      REGISTRY_HEALTH_STORAGEDRIVER_ENABLED: "false"
      REGISTRY_HTTP_TLS_CERTIFICATE: ./data/certs/live/${DOMAIN}/fullchain.pem
      REGISTRY_HTTP_TLS_KEY: ./data/certs/live/${DOMAIN}/privkey.pem
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: "/data/auth/htpasswd"
    volumes:
      - ./data:/data
